# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: ibkr_porez
site_url: https://andgineer.github.io/ibkr-porez-py
site_author: Andrey Sorokin

# Repository
repo_name: ibkr_porez
repo_url: https://github.com/andgineer/ibkr-porez-py
edit_uri: edit/master/docs
docs_dir: 'src/LANGUAGE'
site_dir: 'SITE_DIR'

plugins:
  - awesome-pages
  - search:
      lang: LANGUAGE
  - mkdocstrings:
        handlers:
          python:
            options:
              show_root_heading: true

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: 'docs/includes'
  - admonition

theme:
  name: material
  features:
    - toc.integrate
    - navigation.tracking
    - content.code.copy

extra:
  alternate:
    - name: English
      link: /ibkr-porez-py/
      lang: en
    - name: Русский
      link: /ibkr-porez-py/ru/
      lang: ru
    - name: Українська
      link: /ibkr-porez-py/uk/
      lang: uk
    - name: Srpski (Latinica)
      link: /ibkr-porez-py/rs/
      lang: rs
    - name: Српски (Ћирилица)
      link: /ibkr-porez-py/rs-cyr/
      lang: rs-cyr

nav:
  - index.md
  - installation.md
  - usage.md
  - ibkr.md
